### PR TITLE
Enable 3.5 on travis

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by Carreau** [comment]
will be fixed by next sphinx upgrade.

**Comment by willingc** [comment]
@Carreau The new sphinx version is out. Perhaps trigger Travis to rebuild PR when you have time. I tried without success to do so.

**Comment by takluyver** [comment]
Have prodded Travis.

**Comment by willingc** [comment]
Thanks @takluyver

**Comment by willingc** [comment]
Well it looks like it will be a while longer for Sphinx to merge the fix for HTMLParseError being removed in Python 3.5. I've created a ``.travis.yml`` that tests Python 3.5 but skips the failing ``make linkcheck``.
https://github.com/willingc/jupyter/commit/a31da10991eb265285c89d10f39d32234d722762

**Comment by Carreau** [comment]
> Well it looks like it will be a while longer for Sphinx to merge the fix for HTMLParseError being removed in Python 3.5

the fix is in 2.3.3 let me investigate why it still fails

**Comment by Carreau** [comment]
Works now. travis just needed 1 more kick.

**Comment by willingc** [comment]
@Carreau Well that was easy ;)

**Pull request merged**
