### PR TITLE
Glossary improvements

### PR DESCRIPTION
**Pull request by ericsnekbytes**
This update adds more information and terms related to the Jupyter ecosystem and offerings.

### CODE REVIEW

**Comment by choldgraf** [comment]
This is great - just a quick note - it's IPython, or ipython, but never iPython 🙂

**Comment by ericsnekbytes** [comment]
> This is great - just a quick note - it's IPython, or ipython, but never iPython 🙂

Thanks, I'll update the content :)

**Comment by ericsnekbytes** [comment]
@choldgraf Can you review/merge this?

**Review by afshin — APPROVED** [review]
Thank you! We talked about this during the weekly Jupyter Notebook call and group of us took a look.

**Pull request merged**
