### PR TITLE
a bit of the Russian translation

### PR DESCRIPTION
**Pull request by krote5k**
a bit of the Russian translation
index.po - 100%

### CODE REVIEW

**Comment by parente** [comment]
Thanks for this work @krote5k!

We're in the process of documenting a translation workflow in #475. We've been using Transifex hoping that it'll allow people who aren't familiar with GitHub and `.po` files to contribute and review translations. It'll be interesting to see if Transifex can account for translations made directly to the `.po` files. (It think it can.)

I'll look into getting the `ru_RU` locale setup in both Transifex and ReadTheDocs. Then we can merge this PR and see what happens.

**Comment by choldgraf** [comment]
FYI I just approved the russian locale for Transifex! 🎉

**Comment by krote5k** [comment]
since I started here, I will finish the translation on github

**Comment by parente** [comment]
Thanks @krote5k. Hopefully we can get them imported, even if we have to do it manually once through the Transifex UI. I'm hoping it'll pick them up automatically once we merge, though.

I think I completed all the steps for this to deploy to ReadTheDocs when it merges

image

I'm going to be AFK for a bit but will check in on this PR when I'm back.

**Comment by krote5k** [comment]
a little translation into Russian

**Comment by ivanov** [comment]
@krote5k Thanks for your contribution and your patience here, though I'm not sure about how to proceed

@parente @choldgraf and @willingc : [according to the docs](https://github.com/jupyter/jupyter/blob/master/docs/source/contributing/docs-contributions/doc-new-translation.md), you're our trustworthy translation talent.  I haven't dealt with transifex before, so I have some questions: can we just merge this as is and then import into transifex? Did we stop using transifex? looks like the last update there was 3 years ago. Was it just a victim of the pandemic?

**Pull request closed without merging**
