### PR TITLE
Map of the repos

### PR DESCRIPTION
**Pull request by takluyver**
As shown in the dev meeting. This is still fairly rough - it's missing some of the newer projects (I don't know how much stuff we can fit into one diagram...), and the aesthetics could use some work by someone with design sense.

@ellisonbg I don't want to copy this to the design repo as well, because if there are two copies there's very quickly going to be confusion over which one to use. Feel free to copy it when you've got someone ready to work on it.

Pinging @willingc

### CODE REVIEW

**Comment by willingc** [comment]
Yay!!!! :european_castle: and maps

**Comment by takluyver** [comment]
The file doesn't appear to render correctly in either Firefox or Chrome. We may need to convert it to a PNG with Inkscape to put it in docs.

**Comment by takluyver** [comment]
For quick reference, here's what it looks like:

repos_map

**Comment by damianavila** [comment]
Amazing!! :+1: we should merge this early and iterate later, IMHO...

**Comment by willingc** [comment]
I'm going to merge this now. I will open a follow up PR putting it into the Jupyter RTD documentation.

**Pull request merged**
