### PR TITLE
Doc fix for ENV for data files

### PR DESCRIPTION
**Pull request by vaguiar**
Fix based on issue- https://github.com/jupyter/jupyter_core/issues/138

### CODE REVIEW

**Comment by choldgraf** [comment]
great! thanks very much for this improvement :-)

**Comment by choldgraf** [comment]
Thanks for catching that @takluyver - I'm +1 once Thomas is happy :-)

**Comment by vaguiar** [comment]
thanks. will do

**Comment by choldgraf** [comment]
this one can be closed now - @krinsman documented this variable in addition to the jupyter_paths variable in https://github.com/jupyter/jupyter/pull/450 . Many thanks for giving this PR a kick-start though @vaguiar !

**Pull request closed without merging**
