### PR TITLE
Prototype of Documentation Updated Theme and Organization

### PR DESCRIPTION
**Pull request by willingc**
WIP - [Rendered](http://test-jupyter.readthedocs.org/en/seaside/index.html)

### CODE REVIEW

**Comment by Carreau** [comment]
Neat ! We likely want to limit the max-height of the Jupyter Logo :-) Will try to read-through !

**Comment by rgbkrk** [comment]
Nice!

**Comment by willingc** [comment]
@JamiesHQ If you could start reviewing the structure that would be great. I've rebased so there are no merge conflicts (i.e. green button Merge Pull Request returns). After moving the JupyterHub repos to the JupyterHub org, I need to go back and edit some links in these files. I also want to make sure each section has at least a paragraph (or coming soon) on it. Thanks.

Rendered docs from this PR: http://test-jupyter.readthedocs.org/en/seaside/

Existing jupyter/jupyter docs: http://jupyter.readthedocs.org/en/latest/

**Comment by willingc** [comment]
### Checklist for sections

**Criteria for section completion**
- [ ] Minimal viable content.
- [ ] Editing for readability done.
- [ ] Grammar checked with external Grammarly tool.
- [ ] Section and subsection titles edited for consistency and user helpfulness. See OpenStack docs.
- [ ] Use of Restructured Text elements applied consistently.
- [ ] Links are good.

**Sections**
- [x] Quickstart
- [ ] Architecture
- [ ] Narratives
- [x] IPython
- [x] Installation, Configuration, and Usage
- [ ] Community Guides
- [ ] Contributor Guides
- [ ] Release Notes
- [x] Reference

**Comment by Carreau** [comment]
Quick todo for later. : Next/previous at the bottom of template

**Comment by fperez** [comment]
Other than fixing the currently confusing logo -> index.html and top-bar -> content.html, I'm 👍 on merging this now. It's not perfect, but it improves so much, that we can then iterate further on a merged foundation, rather than holding this up for a long time.

**Comment by willingc** [comment]
@ellisonbg @fperez @Carreau @JamiesHQ @Ruv7 I've made the UI changes that Fernando and Mattias suggested on our last conference call. Thanks to all for your help in pushing this forward. Jamie, the green button goes to you.

[Rendered version](http://test-jupyter.readthedocs.io/en/seaside/index.html)

**Comment by willingc** [comment]
@Carreau Do you have a Google Analytics code that I can use for the Jupyter/jupyter docs? I would like to add it in the RTD settings. Thanks.

**Comment by Carreau** [comment]
Just created `UA-52617120-6` bound to `http://jupyter.readthedocs.io`. I'm  not sure if we can use an id attached to another domain.

**Comment by Carreau** [comment]
> @ellisonbg @fperez @Carreau @JamiesHQ @Ruv7 I've made the UI changes that Fernando and Mattias suggested on our last conference call. Thanks to all for your help in pushing this forward. Jamie, the green button goes to you.

I'll look at that later. Had a few last minutes things to do today.

**Comment by willingc** [comment]
@Carreau Thanks Matthias for the GA code 👍

**Comment by Carreau** [comment]
Miscs things we can adress later:

 - `docs/source/_static/_images/DecideProject_v2.png` text is too small, will be hard to read on small screen. I doubt a flow chart is really necessary at that point.  
 - I doubt we need IPython as a top section in the sidebar.
 - I'm -1 in maintaining an index.htm in template that hardcode the TOCtree, yes I know there is not many other choices for now. 
  - `docs/source/_templates/layout.html` should not hardcode style. 
  - config also possible in JSON files, json files takes precedence over .py files.

**Comment by Carreau** [comment]
Ok, let's move forward, let's merge and refine.

**Comment by willingc** [comment]
@Carreau Thanks! I agree we can refactor the above over time. :cat: :dog:

@ellisonbg @takluyver @jdfreder @minrk If one of you could make me an owner of the Read The Docs account for jupyter/jupyter, I can then drop in the Google Analytics info in their config. Thanks!

Thanks @JamiesHQ @Ruv7 @fperez along with those already mentioned for moving this forward.

**Comment by JamiesHQ** [comment]
@willingc : congrats! great to see it up!

**Comment by takluyver** [comment]
I have added you as a maintainer on the jupyter overview docs.

**Comment by willingc** [comment]
Thanks @takluyver :tulip:

**Comment by takluyver** [comment]
Tulips? Tulips!

Moar tulips

(That's been hanging around in a tag waiting for an excuse to go somewhere)

**Comment by willingc** [comment]
@takluyver Wow, beautiful photo :tulip: My grandma would have loved these.

**Pull request merged**
