### PR TITLE
Fix conda installation procedure

### PR DESCRIPTION
**Pull request by maciejjaskowski**
`conda install jupyter` instead of `conda update jupyter`

### CODE REVIEW

**Comment by ellisonbg** [comment]
That section assumes a user has just downloaded anaconda. In that case, jupyter is already installed and the user just needs to run update rather than install.

**Comment by maciejjaskowski** [comment]
That's what I did on MacosX: I just downloaded anaconda and `conda update
jupyter` didn't work whereas `conda install jupyter` did...

On 24 October 2015 at 04:43, Brian E. Granger <notifications@github.com>
wrote:

> That section assumes a user has just downloaded anaconda. In that case,
> jupyter is already installed and the user just needs to run update rather
> than install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter/pull/55#issuecomment-150743318>.
>



-- 

Twitter: @mjaskowski

**Comment by maciejjaskowski** [comment]
It kept complaining:

> conda update jupyter

Error: package 'jupyter' is not installed in /Users/maciej/anaconda

On 24 October 2015 at 09:37, Maciej Jaśkowski <maciej.jaskowski@gmail.com>
wrote:

> That's what I did on MacosX: I just downloaded anaconda and `conda update
> jupyter` didn't work whereas `conda install jupyter` did...
>
> On 24 October 2015 at 04:43, Brian E. Granger <notifications@github.com>
> wrote:
>
>> That section assumes a user has just downloaded anaconda. In that case,
>> jupyter is already installed and the user just needs to run update rather
>> than install.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jupyter/jupyter/pull/55#issuecomment-150743318>.
>>
>
>
>
> --
>
> Twitter: @mjaskowski
>



-- 

Twitter: @mjaskowski

**Comment by jorisvandenbossche** [comment]
@ellisonbg The bundled Anaconda installer you can download, always lags a bit behind, as it only updates a bunch of packages at certain points, and not each package individually. According to this list, it still includes ipython 3.2: http://docs.continuum.io/anaconda/pkg-docs

Which can be true, as the latest Anaconda 2.3 was released beginning of July

**Comment by maciejjaskowski** [comment]
Hm, sth is definitely wrong.

I removed anaconda and installed it again using
Anaconda3-2.3.0-MacOSX-x86_64.pkg

Then I ran

>  conda list

# packages in environment at /Users/maciej/anaconda:
#
_license                  1.1                      py34_0
...
ipython                   3.2.0                    py34_1
...

and yet I am getting

> conda update jupyter

Error: package 'jupyter' is not installed in /Users/maciej/anaconda


However, at this point

ipython notebook

works smoothly!

I even managed to add R kernel.


On the other hand the install command claims to be fetching missing jupyter
and updates (!) ipython to 4.0.0


> conda install jupyter

Fetching package metadata: ....

Solving package specifications: .

Package plan for installation in environment /Users/maciej/anaconda:


The following packages will be downloaded:


    package                    |            build

    ---------------------------|-----------------

    openssl-1.0.2d             |                0         3.0 MB

    zeromq-4.1.3               |                0         577 KB

    freetype-2.5.5             |                0         732 KB

    qt-4.8.7                   |                1        39.0 MB

    appnope-0.1.0              |           py34_0           4 KB

    certifi-2015.9.6.2         |           py34_0         213 KB

    conda-env-2.4.2            |           py34_0          24 KB

    decorator-4.0.4            |           py34_0           6 KB

    ipython_genutils-0.1.0     |           py34_0          34 KB

    mistune-0.7.1              |           py34_0         151 KB

    path.py-8.1.2              |           py34_0          46 KB

    pexpect-3.3                |           py34_0          62 KB

    pickleshare-0.5            |           py34_0           8 KB

    ptyprocess-0.5             |           py34_0          19 KB

    python-3.4.3               |                2        11.3 MB

    pyzmq-14.7.0               |           py34_1         310 KB

    requests-2.8.1             |           py34_0         647 KB

    setuptools-18.4            |           py34_0         346 KB

    simplegeneric-0.8.1        |           py34_0           6 KB

    sip-4.16.9                 |           py34_0         210 KB

    tornado-4.2.1              |           py34_0         550 KB

    traitlets-4.0.0            |           py34_0          93 KB

    wheel-0.26.0               |           py34_1          77 KB

    conda-3.18.3               |           py34_0         180 KB

    ipython-4.0.0              |           py34_1         973 KB

    jinja2-2.8                 |           py34_0         301 KB

    jupyter_core-4.0.6         |           py34_0          49 KB

    pip-7.1.2                  |           py34_0         1.5 MB

    pyqt-4.11.4                |           py34_0         4.0 MB

    terminado-0.5              |           py34_1          18 KB

    jupyter_client-4.1.1       |           py34_0          92 KB

    nbformat-4.0.1             |           py34_0         114 KB

    ipykernel-4.1.1            |           py34_0         115 KB

    nbconvert-4.0.0            |           py34_0         270 KB

    jupyter_console-4.0.3      |           py34_0          23 KB

    notebook-4.0.6             |           py34_0         4.3 MB

    qtconsole-4.1.0            |           py34_0         129 KB

    ipywidgets-4.1.0           |           py34_0         100 KB

    jupyter-1.0.0              |           py34_0           2 KB

    ------------------------------------------------------------

                                           Total:        69.3 MB


The following NEW packages will be INSTALLED:


    appnope:          0.1.0-py34_0

    ipykernel:        4.1.1-py34_0

    ipython_genutils: 0.1.0-py34_0

    ipywidgets:       4.1.0-py34_0

    jupyter:          1.0.0-py34_0

    jupyter_client:   4.1.1-py34_0

    jupyter_console:  4.0.3-py34_0

    jupyter_core:     4.0.6-py34_0

    nbconvert:        4.0.0-py34_0

    nbformat:         4.0.1-py34_0

    notebook:         4.0.6-py34_0

    path.py:          8.1.2-py34_0

    pexpect:          3.3-py34_0

    pickleshare:      0.5-py34_0

    qtconsole:        4.1.0-py34_0

    simplegeneric:    0.8.1-py34_0

    traitlets:        4.0.0-py34_0

    wheel:            0.26.0-py34_1


The following packages will be UPDATED:


    certifi:          14.05.14-py34_0 --> 2015.9.6.2-py34_0

    conda:            3.14.1-py34_0   --> 3.18.3-py34_0

    conda-env:        2.2.3-py34_0    --> 2.4.2-py34_0

    decorator:        3.4.2-py34_0    --> 4.0.4-py34_0

    freetype:         2.5.2-2         --> 2.5.5-0

    ipython:          3.2.0-py34_0    --> 4.0.0-py34_1

    jinja2:           2.7.3-py34_1    --> 2.8-py34_0

    mistune:          0.5.1-py34_1    --> 0.7.1-py34_0

    openssl:          1.0.1k-1        --> 1.0.2d-0

    pip:              7.0.3-py34_0    --> 7.1.2-py34_0

    ptyprocess:       0.4-py34_0      --> 0.5-py34_0

    pyqt:             4.11.3-py34_0   --> 4.11.4-py34_0

    python:           3.4.3-0         --> 3.4.3-2

    pyzmq:            14.7.0-py34_0   --> 14.7.0-py34_1

    qt:               4.8.6-3         --> 4.8.7-1

    requests:         2.7.0-py34_0    --> 2.8.1-py34_0

    setuptools:       17.1.1-py34_0   --> 18.4-py34_0

    sip:              4.16.5-py34_0   --> 4.16.9-py34_0

    terminado:        0.5-py34_0      --> 0.5-py34_1

    tornado:          4.2-py34_0      --> 4.2.1-py34_0

    zeromq:           4.0.5-0         --> 4.1.3-0


Proceed ([y]/n)?




On 24 October 2015 at 11:23, Joris Van den Bossche <notifications@github.com>
wrote:
>
> @ellisonbg The bundled Anaconda installer you can download, always lags a
bit behind, as it only updates a bunch of packages at certain points, and
not each package individually. According to this list, it still includes
ipython 3.2: http://docs.continuum.io/anaconda/pkg-docs
>
> Which can be true, as the latest Anaconda 2.3 was released beginning of
July
>
> —
> Reply to this email directly or view it on GitHub.




--

Twitter: @mjaskowski

**Comment by damianavila** [comment]
I would accept this one until the next installers containing jupyter exists and then revert back after that point...

**Comment by damianavila** [comment]
>I would accept this one until the next installers containing jupyter exists and then revert back after that point...

Well anaconda 2.4 will be released soon... so maybe it is not worth the make the change...

**Comment by ellisonbg** [comment]
Damian,

Can you confirm that Anaconda 2.4 will include the jupyter package? How
soon is the release?

Brian

On Tue, Oct 27, 2015 at 3:16 PM, Damián Avila <notifications@github.com>
wrote:

> I would accept this one until the next installers containing jupyter
> exists and then revert back after that point...
>
> Well anaconda 2.4 will be released soon... so maybe it is not worth the
> make the change...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter/pull/55#issuecomment-151614992>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
@damianavila doesn't `install` trigger upgrade if it's already present? That would mean this is always correct, whereas upgrade is only correct when it's already present.

**Comment by maciejjaskowski** [comment]
That's how it seems to work:

> conda list
(...)

zlib                      1.2.8                         0


> conda install zlib

Fetching package metadata: ....

Solving package specifications: ................

Package plan for installation in environment /Users/maciej/anaconda:


The following packages will be downloaded:


    package                    |            build

    ---------------------------|-----------------

    conda-env-2.4.4            |           py34_0          24 KB


The following packages will be UPDATED:


    conda-env: 2.4.2-py34_0 --> 2.4.4-py34_0


Proceed ([y]/n)? y

(...)

> conda install zlib

(...)

# All requested packages already installed.

# packages in environment at /Users/maciej/anaconda:

#

zlib                      1.2.8                         0

On 28 October 2015 at 10:34, Min RK <notifications@github.com> wrote:

> @damianavila <https://github.com/damianavila> doesn't install trigger
> upgrade if it's already present? That would mean this is always correct,
> whereas upgrade is only correct when it's already present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter/pull/55#issuecomment-151780077>.
>



-- 

Twitter: @mjaskowski

**Comment by minrk** [comment]
@maciejjaskowski thanks.

**Comment by damianavila** [comment]
>Can you confirm that Anaconda 2.4 will include the jupyter package? How
soon is the release?

Yes, confirmed and I think it will be this week...

> @damianavila doesn't install trigger upgrade if it's already present? That would mean this is always correct, whereas upgrade is only correct sometimes.

Yep... `conda update` should be also always valid after 2.4 release, but I am ok to see this merged for now...

**Comment by minrk** [comment]
Bonus for install: it works for miniconda, and conda envs, not just anaconda installs.

**Pull request merged**
