### PR TITLE
Update install.rst

### PR DESCRIPTION
**Pull request by matt2000**
Add command parameters to ensure jupyter command is available globally.

### CODE REVIEW

**Comment by takluyver** [comment]
Using sudo with pip is strongly recommended against in general. I don't
want our installation docs to suggest it.

**Comment by tacaswell** [comment]
Second to not documenting using `sudo` with `pip`.  If you _should_ be installing system wide you will know how to do it.

If these docs are updated, they should be extended to using venv.

**Comment by takluyver** [comment]
For reference, I install things like jupyter with pip's --user option,
which installs it under my home directory. The only reason I don't tend to
document that is that the bin folder is not in PATH by default in most
systems.

**Comment by willingc** [comment]
@matt2000 Thanks for submitting the pull request. Although we don't plan to merge this PR, I do appreciate the effort. I'm a bit curious what operating system that you are working with and under which conditions you believe that this command is necessary.

I'm going to close this PR. Thanks again.

**Comment by matt2000** [comment]
I'm on Ubuntu 16.04, and admittedly am not very familiar with using pip to install full applications (as opposed to python libraries). So for others like me, it seems a step is missing to make the `jupyter` command available. I imagine the preferred way to do it is add the jupyter/bin folder to one's PATH explicitly?

**Comment by takluyver** [comment]
Yeah, we kind of assume that people following the `pip` section of the docs will have already done that, or know to use a virtualenv. It's hard to provide specific instructions because of the different ways people like to do things. It is annoying that `~/.local/bin` isn't on PATH by default.

If you install using Anaconda, it sorts out adding itself to PATH.

**Comment by takluyver** [comment]
(To be clear, I'm acknowledging that our instructions do currently assume that - not saying they should)

**Pull request closed without merging**
