### PR TITLE
No recording policy

### PR DESCRIPTION
**Pull request by JasonWeill**
Fixes https://github.com/jupyterlab/team-compass/issues/214 by documenting request not to record Jupyter meetings.

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Thanks a lot @JasonWeill for this improvement.

**Comment by krassowski** [comment]
It looks we need to add `.readthedocs.yml` probably parts can be copied from https://github.com/jupyter/nbdime/pull/686

**Comment by JasonWeill** [comment]
Migrated the readthedocs config; thanks @krassowski

**Comment by isabela-pf** [comment]
Thank you for making the time to write this up! I'm happy to have this here.

**Pull request merged**
