### PR TITLE
Add page for custom mimetypes

### PR DESCRIPTION
**Pull request by willingc**
Documentation for https://github.com/jupyter/jupyter_client/issues/207

cc @minrk @ellisonbg

### CODE REVIEW

**Comment by Carreau** [comment]
That's a good start ! Thanks ! We can refine later !

**Comment by minrk** [comment]
cc @rgbkrk

**Comment by rgbkrk** [comment]
Excellent, thank you!

**Comment by rgbkrk** [comment]
Went ahead and swapped out the deprecated mimetype for nteract in https://github.com/nteract/nteract/pull/906.

**Comment by flying-sheep** [comment]
Hi! I see the page on https://jupyter.readthedocs.io/en/latest/reference/mimetype.html

But vega is missing. Anything else?

**Pull request merged**
