### PR TITLE
Change contributing section structure

### PR DESCRIPTION
**Pull request by GeorgianaElena**
- Fixed IPython development guide doubled in the left TOC
- Moved sub-pages of developer guide into subsections on the same page (contributing prs, submitting bugs, reporting vulnerabilities)
- Moved contributing for the first time to “get started contributing” page
- Renamed some of the contributing doc source files and moved them in one big `contributing` directory

### CODE REVIEW

**Comment by choldgraf** [comment]
This looks really good to me! I think that the one penalty we'll have here is re-arranging content, which might lead to some dead links and a penalty to SEO. I also wonder if this will provide problems for transifex translations? (@parente do you have any thoughts on that?)

That said, I think that it is worth-it if our content is organized in a way that is both easier to read and discover, and easier to maintain. So I'm +1 on the idea.

I'll hold off on merging this or your other PR for a few days to give others a chance to weigh in on that matter. What do you think @GeorgianaElena ?

**Comment by parente** [comment]
> I also wonder if this will provide problems for transifex translations? (@parente do you have any thoughts on that?)

If source strings move to a new file, Sphinx won't automatically map translations that exist for them to those new files. Translators need to provide translations for the strings in the new documents. Transifex assists with that, I believe, by indicating that a translation already assists for a string of text elsewhere. But someone still needs to click buttons.  It probably isn't a terrible cost at present. It is something to keep in mind as the number of translations grows.

image

There may be ways to migrate translations across language .po files automatically. I haven't looked into it.

**Comment by choldgraf** [comment]
OK - in that case perhaps we should merge this and see what happens. Looking here:

https://github.com/jupyter/jupyter/blob/master/docs/.tx/config

It doesn't seem like a ton of the contributor documentation was translated? We can try to spot-check the translations if they get broken by a merge?

**Comment by choldgraf** [comment]
OK I'm gonna give @GeorgianaElena's two PRs a merge and let's see how that affects the translation stuff. If we need a manual step I am happy to help figuring out how to get stuff moved over.

Thanks @GeorgianaElena for making these improvements, I am excited!

**Pull request merged**
