### PR TITLE
docs – Use-Cases: Jupyter in the Enterprise

### PR DESCRIPTION
**Pull request by jhermann**

### CODE REVIEW

**Comment by jhermann** [comment]
I have no more resources right now, so this is ready. @choldgraf @willingc

**Comment by choldgraf** [comment]
@jhermann I made a commit to your PR with very minor edits (I added line breaks and also slightly changed the wording of the final "note"). Does that work for you?

I'll leave this open for a little bit to give others a chance to comment if they have thoughts!

**Comment by jhermann** [comment]
:+1:

**Comment by willingc** [comment]
@jhermann Thought you would like to see this deployed https://jupyter.readthedocs.io/en/latest/use-cases/enterprise.html

**Pull request merged**
