### PR TITLE
mention build dependencies when installing with pip

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by willingc** [comment]
@minrk Was there a particular reason that you are using ``pip3`` versus ``pip`` for all? Assuming for those with older versions of ``pip``.

**Comment by Carreau** [comment]
It's common on system that have both python 2 and 3 to have pip/pip3/python/python3 to explicitly differentiate. Which is the case this part of the docs cover.

**Comment by willingc** [comment]
@minrk and @Carreau: I think it's fine if we use ``pip3`` but it may be good from a maintenance standpoint to use start shifting to ``python -m pip install jupyter`` for all but python 2.6. See attached conversation with Donald Stufft, maintainer of pip, pypa.

screen shot 2015-09-22 at 9 58 21 am

**Comment by minrk** [comment]
I'm okay with `python -m pip`. We haven't supported Python 2.6 for some time, so we don't need to worry about that.

**Comment by Carreau** [comment]
Ok, let's merge, iterate on that, and try to push `python -m pip`.

**Comment by willingc** [comment]
@Carreau @minrk Sounds good :smile:

**Pull request merged**
