### PR TITLE
Fix diagrams by reinstating graphiz

### LINKED ISSUE #700: Diagram does not show up in the documentation "Usage"
Screenshot from 2023-10-11 16-25-57

### PR DESCRIPTION
**Pull request by krassowski**
Fixes #700 - which I was wrongly accused of! ;)

### CODE REVIEW

**Comment by krassowski** [comment]
Well it does fix it but only partially:

image

I got no more time to put into it right now, hopefully someone else can pick it up.

**Comment by krassowski** [comment]
CC @ivanov

**Comment by ivanov** [comment]
**high five** we got it - it was the size that was throwing things off, looks like size only works properly for png output.

**Comment by krassowski** [comment]
Thanks!

**Pull request merged**
