### PR TITLE
correct command to run notebook

### PR DESCRIPTION
**Pull request by dselivanov**

### CODE REVIEW

**Comment by minrk** [comment]
The correct command is `jupyter notebook`. `notebook` is a subcommand of `jupyter`.

**Comment by dselivanov** [comment]
10 minutes ago I installed `jupyter`:
```
sudo pip install -U jupyter
```
And I don't have `jupyter` commad, only `jupyter-console      jupyter-kernelspec   jupyter-nbconvert    jupyter-nbextension  jupyter-notebook     jupyter-qtconsole    jupyter-trust `. What I'm doing wrong?

**Comment by minrk** [comment]
@dselivanov what OS, Python, and pip version? It may not be you doing something wrong, it could be something in our packaging.

**Comment by dselivanov** [comment]
Python 2.7.10, OS X 10.10,  pip 7.1.2

**Comment by dselivanov** [comment]
any thoughts?

**Comment by minrk** [comment]
I'm trying to figure out what could have gone wrong, since that's exactly my version of everything. What's your `pip list`, `which jupyter` and `which jupyter-notebook`? And what do you get from `jupyter -h`?

**Comment by dselivanov** [comment]
`which jupyter` is simply empty, so `jupyter -h` gives: 
> jupyter: command not found`

`which jupyter-notebook`
> /usr/local/bin/jupyter-notebook

`pip list`:
> appnope (0.1.0)
backports-abc (0.4)
backports.ssl-match-hostname (3.4.0.2)
boto (2.38.0)
Bottleneck (1.0.0)
bz2file (0.98)
certifi (2015.9.6.2)
CherryPy (3.8.0)
Cython (0.23.4)
decorator (4.0.4)
ecdsa (0.13)
Fabric (1.10.2)
functools32 (3.2.3-2)
gensim (0.12.3)
glove (0.0.1, /Users/dmitryselivanov/projects/glove-python)
gnureadline (6.3.3)
hat-trie (0.2)
httpretty (0.8.6)
ipykernel (4.1.1)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.0.3)
jupyter-core (4.0.6)
marisa-trie (0.7.2)
MarkupSafe (0.23)
mistune (0.7.1)
msgpack-python (0.4.6)
nbconvert (4.1.0)
nbformat (4.0.1)
notebook (4.0.6)
numpy (1.10.1)
paramiko (1.16.0)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (7.1.2)
ptyprocess (0.5)
pycrypto (2.6.1)
Pygments (2.0.2)
python-utils (1.6.2)
pyzmq (15.0.0)
qtconsole (4.1.0)
requests (2.8.1)
scikit-learn (0.16.1)
scipy (0.16.1)
setuptools (18.3.1)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
smart-open (1.3.0)
terminado (0.5)
tornado (4.3)
traitlets (4.0.0)
wheel (0.26.0)

**Comment by minrk** [comment]
The `jupyter` executable is provided by `jupyter-core`, so I'm not sure how pip failed to install it or removed it. You can try reinstalling:

    pip uninstall jupyter-core
    pip install jupyter-core

**Comment by dselivanov** [comment]
Thanks! reinstalling `jupyter-core` solved all the problems.

**Comment by minrk** [comment]
If you have a record of the order of installs you did, we might be able to reproduce the situation, but I'm not sure how to do that on purpose at this point.

**Pull request closed without merging**
