### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by ggold7046**
Fixed typo.

### CODE REVIEW

**Comment by chunqiaohu** [comment]
您好，您的邮件我已经收到，会尽快给您回复，谢谢。

**Comment by ggold7046** [comment]
Can I close this issue ?

**Comment by ggold7046** [comment]
Hi, any update on this issue ?

**Comment by ivanov** [comment]
Hi @ggold7046 -sorry it took so long, but I find the comma there grammatically correct.  Closing this, but please do submit other things you find in the future.

**Pull request closed without merging**
