### PR TITLE
updating theme and some section titles

### PR DESCRIPTION
**Pull request by choldgraf**
This PR updates our Jupyter documentation theme to use the new [pandas sphinx theme](https://github.com/pandas-dev/pandas-sphinx-theme). (calling it a "pandas" theme is a bit of a misnomer, we've been contributing to this theme for a bit now, and [many of the jupyterhub docs have switched over to it already](http://z2jh.jupyter.org/en/latest/)).

The current Jupyter docs are built on bootstrap, and so is the pandas docs theme, so changing things should be a fairly minimal process. Here are the key changes I needed to make, other than just changing the theme:

* Some section titles were shortened to accommodate the horizontal space at the top
* I removed one section (Releases) because it was empty in order to have enough space
* The logo is now in the nav bar instead of manually embedded in each page w/ a template. Same thing for the "next / prev" page buttons

preview here: https://74-36895421-gh.circle-artifacts.com/0/html/index.html

## An example page

Here's the current docs:

image

and the new version:

image

What do folks think? There will likely be more tweaks that need to be made, but I wanted to give a preview of how it looks first to see if others were interested in it. If so, I'm happy to get it ready to merge. This site gets a decent amount of traffic, so it would be fantastic if we can start making some iterative improvements to it

### CODE REVIEW

**Comment by choldgraf** [comment]
Hey all - pydata sphinx theme is now released on pypi, so I think we can merge this if folks are +1 on the theme change.

I am a strong +1

maybe @willingc has thoughts, since put in a ton of work on the current theme?

**Comment by choldgraf** [comment]
Note: I am also happy to merge this PR in...I am hesitant to do so to make sure that others are OK on the decision, but if PR bandwidth is a bottleneck here, I am also happy to do a bit of cleanup/general improvements/self-merge. What do you think @parente ?

**Comment by willingc** [comment]
@choldgraf +1 for me. A former summer intern gets credit for the theme.

**Comment by willingc** [comment]
@choldgraf So much nicer. It's live now. There's some minor formatting to do on the landing page: https://jupyter.readthedocs.io/en/latest/

**Comment by choldgraf** [comment]
yay! thanks @willingc - is it OK if I self-merge in some formatting spot-checks in the coming days?

**Pull request merged**
