### PR TITLE
[WIP] Change documentation landing page and contents to reflect dev meeting input

### PR DESCRIPTION
**Pull request by willingc**
Please do not merge.

### CODE REVIEW

**Comment by willingc** [comment]
Here is a rough draft of a read the docs landing page which the Documentation tab of the Jupyter website will link to. Down the road this will be a more visual page similar to docs.openstack.org which will require design assistance. For now, I would appreciate a review of the [basic outline and sections rendered here](http://test-jupyter.readthedocs.org/en/landing/). 

cc/ @fperez @ellisonbg @Ruv7 following up from our communications breakout at dev meeting.

**Comment by takluyver** [comment]
Another landing page I quite like is https://docs.python.org/3/ . Both Openstack and Python use a two-column layout (on large enough screens, anyway), and titles with a subtext to provide more explanation of what that link offers. Perhaps these are design elements that we can ~~copy~~ steal?

**Comment by takluyver** [comment]
Content-wise, I would cut out the first three paragraphs ('welcome' + what is it) entirely. I think 98% of people reaching the docs will already have an idea what Jupyter is and skip the description, and it's too abstract to be helpful to people who don't know it. Space at the top of the landing page is really valuable, and I don't think this is important enough to be there.

We could have a 'What is Jupyter' link, but I think that needs to be written more like 'Why should I care about Jupyter', rather than a definition. I can have a go at writing that if you want.

I think we're using the rather vague term 'project' too much. We refer to specific repositories/packages as projects, but also to *Project Jupyter*. Maybe 'components' is a better term for the repos/packages that are parts of Jupyter and IPython. It's also more specific to code - e.g. Jupyter Days could be called a 'project', but it's quite a different kind of thing from the pieces of code.

**Comment by willingc** [comment]
@takluyver Great suggestions. The only critical piece of info to convey upfront is that this is the landing page for all Jupyter documentation since more than one person felt it was disorienting to go from the Jupyter website to this page on RTD. I'll create a two column version tomorrow and ping folks when it's in a draft state.

**Comment by willingc** [comment]
Closing - #134 replaced this with a different approach.

**Pull request closed without merging**
