### PR TITLE
📚 DOCS: updating a page to myst

### PR DESCRIPTION
**Pull request by choldgraf**
Here's a first step at using myst in these docs. This PR replaces `recommonmark` with `myst`, and converts the `index.rst` page into MyST markdown. I was thinking that we could then create an issue to convert over the remaining pages.

### CODE REVIEW

**Comment by choldgraf** [comment]
@willingc I was thinking about adding an issue to any repository we wanna convert over to myst, and then tagging it for Hacktoberfest to see if others would be interested in helping make those conversions. @sgibson91 do you think that'd be a nicely-scoped topic for hacktoberfest?

**Comment by sgibson91** [comment]
I think yes it's well scoped, but I think it's one for someone who is already familiar with myst maybe?

**Comment by choldgraf** [comment]
Ah you know what, I forgot that someone on the executablebooks project is actually working on a little sphinx extension to facilitate rST -> MyST conversion, so perhaps we should wait to use that once it's ready:

https://github.com/mmcky/sphinxcontrib-tomyst

**Comment by BigD1CKC** [comment]
dope

**Review by willingc — APPROVED** [review]
@choldgraf 👍

**Comment by willingc** [comment]
@choldgraf Thanks for the this. Merged and it is building now. FYI, I had to go in and wipe the `latest` version and rebuild for it not to fail. Just in case you see something in the future getting rid of the old RTD container by wiping should help.

**Pull request merged**
